### ISSUE TITLE
Editing post in multiple browsers has unexpected experience. 

### ISSUE THREAD

**Issue by alankley** [scripting/wordlandSupport#17]
Is editing a site using WordLand using multiple tabs in same browser or in different browsers intended to be supported?  Does WordLand try to assure there is only one active editing tab?

I logged in to WordLand (and thus my Wordpress site) on Google Chrome and Microsoft Edge.

When one window received focus it displays the **"WordLand is running in another tab. You must reload this one, or - you can safely close it."**

It's not clear from the message what is going on or what I need to do.
There were no pending unsaved changes.
When popup message was dismissed it appeared to refresh, I assume it reloads. How is user suppose to "reload" ?  Refresh the browser page?

If one browser is viewing a different post, the 2nd one is updated to view that post when the popup message is dismissed.

Not sure what the expected behavior.  Video attached.

https://github.com/user-attachments/assets/3c580957-bcff-4d40-96f4-cc40c02bb891

**Comment by scripting** [comment]
@alankley -- great report! :-)

I like the video and that shows the software is working as designed. I've never actually run that test myself. ;-)

To answer your question -- you can only have the editor open in one browser tab at a time. When you click OK it is indeed reloading on its own, thus the message is confusing. I'll think about how to make it make more sense. 

Keep asking questions, this is great stuff.
